mysql:
    image: mysql:5.7.11
    environment:
        - MYSQL_ROOT_PASSWORD=root
apache-php:
    image: php:5.4-apache
    ports:
        - "80:80"
    volumes:
        - ./:/var/www/html
        - ./data/conf/:/etc/apache2/conf-enabled
    links:
        - mysql:db
phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.5.3.1-1
    ports:
        - "8080:8080"
    links:
        - mysql:db

