<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/02/14 17:37:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=employee-mgr',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
